services:
  postgres:
    image: postgres:16
    container_name: pms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pms
    ports:
      - "5432:5432"
    volumes:
      - pms_pgdata:/var/lib/postgresql/data

volumes:
  pms_pgdata:
